name: pudez_plogging
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  smooth_page_indicator: ^1.2.0+3
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Black.ttf
          weight: 900

  assets:
    - assets/images/onboarding/onboarding_1/
    - assets/images/onboarding/onboarding_2/

    - assets/images/character/character_0/
    - assets/images/character/character_1/
    - assets/images/character/character_2/
